### PR TITLE
Upgrade cursor from 0.39.0 to 0.40.4

### PR DESCRIPTION
**Pull request by publicfacingusername**
I see the [cursoride](https://community.chocolatey.org/packages/cursoride) package on Chocolately is referencing this repo. I'd like to upgrade the version of Cursor to the latest release.

Tested by:

1. Downloading the latest Cursor exe from https://www.trycursor.com/
2. Running `Get-FileHash '~/path/to/Cursor Setup 0.40.4 - x64.exe' -Algorithm SHA256 | select hash -ExpandProperty hash`
3. Updating the `checksum` in `tools/chocolateyinstall.ps1`
4. Running `choco pack` to generate the .nupkg file
5. Running `choco install cursoride --source .`

### CODE REVIEW

**Comment by targed** [comment]
Thank you for bringing this to my attention. I was unaware that there was a new version of Cursor out. I have updated and pushed it to the community repository. 

To keep more on top of this, would you like me to add you as a maintainer to the package? If you give me your username I can add you and you can run the auto-updater script whenever there is a new version.

**Comment by publicfacingusername** [comment]
If you'd like that's fine by me. My username is the same as here - publicfacingusername. I'll take a look at the script. Thank you!

**Comment by targed** [comment]
Sounds good. I already pushed the latest version of cursor to the community repository. So @ me next time a new version of cursor comes out and I'll make sure to add you. Have a great day!

**Comment by targed** [comment]
I just pushed a new version and added you as a maintainer.

**Pull request closed without merging**
